### ISSUE TITLE
Jupyter notebook read-only

### ISSUE THREAD

**Issue by kwhkim** [mimoralea/gdrl#12]
Hello,

  I am just testing with your codes.

  And I see there is no error that I have to intervene with, that's great.

  But I see that scripts are all read-only. Is there anyway I can edit and save?

  I new to docker so please be kind :)

**Comment by JulesVerny** [comment]
I also observed similar issues, and get a number of annoying warnings and prompts, stating that notebooks cannot be saved, and my modifications are not being saved etc. I wonder if there is a simple way to disable those warnings.
Otherwise the use of docker and notebooks is really good way of avoiding all the installation hassles. I am just hoping that these warnings do not stop me progressing through the book.     

** OK I can avoid getting any Jupyter warnings and notifications by Running in FireFox browser, and not Microsoft Edge Browser.
