### ISSUE TITLE
PicklingError: Can't pickle <function <lambda> at 0x7fc295d89ee0>: attribute lookup <lambda> on __main__ failed

### ISSUE THREAD

**Issue by sonelu** [mimoralea/gdrl#17]
When running A3C  in chapter 11 the above error is issued when `[w.start() for w in workers]` is run.

This seems to be related to the fact that pytorch uses ForkingPickle when starting a process and lambda functions are not supported for pickling.

**Comment by mimoralea** [comment]
Are you using the provided container or some other version of PyTorch?

**Comment by DKilkenny** [comment]
I also had this issue and I can't find a way to update it. I realize I'm not running the docker container but do you have any ideas about how to update this code or fix this issue? Been wracking my brain for a couple of days.
```Python=3.9.10
torchvision               0.2.2                      py_3    pytorch
multiprocess              0.70.12.2        py39h5161555_1    conda-forge
pytorch                   1.10.1          cpu_py39hbfdb42d_0    conda-forge

**Comment by ghost** [comment]
I run A3C successfully on the Windows 10 64 bits and Jupyter Notebook. Python cannot pickle nested functions and lambda functions, so need a hack of code restructure which cost me multiple weeks to trial.  I did not use dill packages, which can pickle more types of variables. While I cannot guarantee it works on other platforms and compilers, you can have a try.

(a) The get_make_env_fn cannot be used. I split the make_env_fn into a .py file (almost all the codes are stored in this .py file), and invented a variable called make_env_kargs = {'env_name': env_name} in a .ipynb file. (Pls note it requires if __name__ == '__init__' in the beginning of .ipynb files)

(b) Avoid and delete all the lambda functions in the .ipynb file, instead you instantiate all object in the functions which is stored in the same .py file as above. For example in the train function:

```
self.shared_policy_model = FCDAP(nS, nA, hidden_dims=(128,64)).share_memory()
self.shared_policy_optimizer = SharedAdam(self.shared_policy_model.parameters(), 
                                                  self.policy_optimizer_lr)
 self.shared_value_model = FCV(nS, hidden_dims=(256,128)).share_memory()
 self.shared_value_optimizer = SharedRMSprop(self.shared_value_model.parameters(), 
                                                    self.value_optimizer_lr)
```

or in work function,

```
local_policy_model = FCDAP(nS, nA, hidden_dims=(128,64))
local_value_model = FCV(nS, hidden_dims=(256,128))
```

But using Windows 10 and Jupyter need to compromise, because now the debug message appear in the terminal(the black screen). Rather using the print function, I write all the message into a txt file during work function and display the text from that txt file in the train function in Jupyter Notebook (not terminal), but the message will be displayed 'all at once' after each training episode, and the print flushing function (the number counter you see in the previous chapter) no longer works.

Multiprocessing is very difficult to use and can come up with many unexpected results. I believe A3C is the first algorithm in this book that many readers hits the wall. It takes me 3 months to rewrite the code in chapter 11 and 12 to implement successfully in Jupyter Notebook, but after all it is very satisfying to complete the whole book.
